# Vendor Boot configuration
TARGET_NO_RECOVERY := true
BOARD_BOOT_HEADER_VERSION := 4

# Use vendor_boot.img
BOARD_USES_VENDOR_BOOT_IMAGE := true
BOARD_USES_GENERIC_KERNEL_IMAGE := true

# Include recovery ramdisk and resources
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_MOVE_GSI_AVB_KEYS_TO_VENDOR_BOOT := true

# Compression
BOARD_RAMDISK_USE_LZ4 := true

# Kernel image
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_INCLUDE_DTB_IN_BOOTIMG := false
BOARD_KERNEL_SEPARATED_DTBO := true

# AVB
BOARD_AVB_VENDOR_BOOT_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_VENDOR_BOOT_ALGORITHM := SHA256_RSA4096
BOARD_AVB_VENDOR_BOOT_ROLLBACK_INDEX := 1
BOARD_AVB_VENDOR_BOOT_ROLLBACK_INDEX_LOCATION := 1

# Vendor boot partition size
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 104857600

